// Utility file

// TODO: Implement more following: https://home.kpn.nl/vanadovv/BignumbyN.html
const suffixList = [
    ["Thousand", "K"],
    ["Million", "M"],
    ["Billion", "B"],
    ["Trillion", "T"],
    ["Quadrillion", "Qa"],
    ["Quintillion", "Qi"],
    ["Sextillion", "Sx"],
    ["Septillion", "Sp"],
    ["Octillion", "Oc"],
    ["Nonillion", "No"],
    ["Decillion", "Dc"],
    ["Undecillion", "Ud"],
    ["Duodecillion", "Dd"],
    ["Tredecillion", "Td"],
    ["Quattuordecillion", "Qad"],
    ["Quindecillion", "Qid"],
    ["Sexdecillion", "Sxd"],
    ["Septendecillion", "Spd"],
    ["Octodecillion", "Ocd"],
    ["Novemdecillion", "Nod"],
    ["Vigintillion", "Vg"],
    ["Unvigintillion", "Uvg"],
    ["Duovigintillion", "Dvg"],
    ["Trevigintillion", "Tvg"],
    ["Quattuorvigintillion", "Qavg"],
    ["Quinvigintillion", "Qivg"],
    ["Sexvigintillion", "Sxvg"],
    ["Septenvigintillion", "Spvg"],
    ["Octovigintillion", "Ocvg"],
    ["Novemvigintillion", "Novg"],
    ["Trigintillion", "Tg"],
    ["Untrigintillion", "Utg"],
    ["Duotrigintillion", "Dtg"],
    ["Tretrigintillion", "Ttg"],
    ["Quattuortrigintillion", "Qatg"],
    ["Quintrigintillion", "Qitg"],
    ["Sextrigintillion", "Sxtg"],
    ["Septentrigintillion", "Sptg"],
    ["Octotrigintillion", "Octg"],
    ["Novemtrigintillion", "Notg"],
    ["Quadragintillion", "Qag"],
    ["Unquadragintillion", "Uqag"],
    ["Duoquadragintillion", "Dqag"],
    ["Trequadragintillion", "Tqag"],
    ["Quattuorquadragintillion", "Qaqag"],
    ["Quinquadragintillion", "Qiqag"],
    ["Sexquadragintillion", "Sxqag"],
    ["Septenquadragintillion", "Spqag"],
    ["Octoquadragintillion", "Ocqag"],
    ["Novemquadragintillion", "Noqag"],
    ["Quinquagintillion", "Qig"],
    ["Unquinquagintillion", "Uqig"],
    ["Duoquinquagintillion", "Dqig"],
    ["Trequinquagintillion", "Tqig"],
    ["Quattuorquinquagintillion", "Qaqig"],
    ["Quinquinquagintillion", "Qiqig"],
    ["Sexquinquagintillion", "Sxqig"],
    ["Septenquinquagintillion", "Spqig"],
    ["Octoquinquagintillion", "Ocqig"],
    ["Novemquinquagintillion", "Noqig"],
    ["Sexagintillion", "Sxg"],
    ["Unsexagintillion", "Usxg"],
    ["Duosexagintillion", "Dsxg"],
    ["Tresexagintillion", "Tsxg"],
    ["Quattuorsexagintillion", "Qasxg"],
    ["Quinsexagintillion", "Qisxg"],
    ["Sexsexagintillion", "Sxsxg"],
    ["Septensexagintillion", "Spsxg"],
    ["Octosexagintillion", "Ocsxg"],
    ["Novemsexagintillion", "Nosxg"],
    ["Septuagintillion", "Spg"],
    ["Unseptuagintillion", "Uspg"],
    ["Duoseptuagintillion", "Dspg"],
    ["Treseptuagintillion", "Tspg"],
    ["Quattuorseptuagintillion", "Qaspg"],
    ["Quinseptuagintillion", "Qispg"],
    ["Sexseptuagintillion", "Sxspg"],
    ["Septenseptuagintillion", "Spspg"],
    ["Octoseptuagintillion", "Ocspg"],
    ["Novemseptuagintillion", "Nospg"],
    ["Octogintillion", "Ocg"],
    ["Unoctogintillion", "Uocg"],
    ["Duooctogintillion", "Docg"],
    ["Treoctogintillion", "Tocg"],
    ["Quattuoroctogintillion", "Qaocg"],
    ["Quinoctogintillion", "Qiocg"],
    ["Sexoctogintillion", "Sxocg"],
    ["Septenoctogintillion", "Spocg"],
    ["Octooctogintillion", "Ococg"],
    ["Novemoctogintillion", "Noocg"],
    ["Nonagintillion", "Nog"],
    ["Unnonagintillion", "Unog"],
    ["Duononagintillion", "Dnog"],
    ["Trenonagintillion", "Tnog"],
    ["Quattuornonagintillion", "Qanog"],
    ["Quinnonagintillion", "Qinog"],
    ["Sexnonagintillion", "Sxnog"],
    ["Septennonagintillion", "Spnog"],
    ["Octononagintillion", "Ocnog"],
    ["Novemnonagintillion", "Nonog"],
    ["Centillion", "C"], // 303 Zeros after digit and is 10^303
    ["Uncentillion", "Uc"],
    ["Duocentillion", "Dc"],
    ["Trescentillion", "Tc"],
    ["Quattuorcentillion", "Qac"],
    ["Quinquacentillion", "Qic"],
    ["Sexcentillion", "Sxc"],
    ["Septencentillion", "Spc"],
    ["Octocentilion", "Occ"],
    ["Novencentilion", "Noc"],
    ["Decicentillion", ""],
    ["Undecicentillion", ""],
    ["Duodecicentillion", ""],
    ["Tredecicentillion", ""],
    ["Quattuordecicentillion", ""],
    ["Quinquadecicentillion", ""],
    ["Sedecicentillion", ""],
    ["Septendecicentillion", ""],
    ["Octodecicentillion", ""],
    ["Novendecicentillion", ""],
    ["Viginticentillion", ""],
    ["Unviginticentillion", ""],
    ["Duoviginticentillion", ""],
    ["Tresviginticentillion", ""],
    ["Quattuorviginticentillion", ""],
    ["Quinquaviginticentillion", ""],
    ["Sesviginticentillion", ""],
    ["Septemviginticentillion", ""],
    ["Octoviginticentillion", ""],
    ["Novemviginticentillion", ""],
    ["Trigintacentillion", ""],
    ["Untrigintacentillion", ""],
    ["Duotrigintacentillion", ""],
    ["Trestrigintacentillion", ""],
    ["Quattuortrigintacentillion", ""],
    ["Quinquatrigintacentillion", ""],
    ["Sestrigintacentillion", ""],
    ["Septentrigintacentillion", ""],
    ["Octotrigintacentillion", ""],
    ["Noventrigintacentillion", ""],
    ["Quadragintacentillion", ""],
    ["Unquadragintacentillion", ""],
    ["Duoquadragintacentillion", ""],
    ["Tresquadragintacentillion", ""],
    ["Quattuorquadragintacentillion", ""],
    ["Quinquaquadragintacentillion", ""],
    ["Sesquadragintacentillion", ""],
    ["Septenquadragintacentillion", ""],
    ["Octoquadragintacentillion", ""],
    ["Novenquadragintacentillion", ""],
    ["Quinquagintacentillion", ""],
    ["Unquinquagintacentillion", ""],
    ["Duoquinquagintacentillion", ""],
    ["Tresquinquagintacentillion", ""],
    ["Quattuorquinquagintacentillion", ""],
    ["Quinquaquinquagintacentillion", ""],
    ["Sesquinquagintacentillion", ""],
    ["Septenquinquagintacentillion", ""],
    ["Octoquinquagintacentillion", ""],
    ["Novenquinquagintacentillion", ""],
    ["Sexagintacentillion", ""],
    ["Unsexagintacentillion", ""],
    ["Duosexagintacentillion", ""],
    ["Tresexagintacentillion", ""],
    ["Quattuorsexagintacentillion", ""],
    ["Quinquasexagintacentillion", ""],
    ["Sesexagintacentillion", ""],
    ["Septensexagintacentillion", ""],
    ["Octosexagintacentillion", ""],
    ["Novensexagintacentillion", ""],
    ["Septuagintacentillion", ""],
    ["Unseptuagintacentillion", ""],
    ["Duoseptuagintacentillion", ""],
    ["Treseptuagintacentillion", ""],
    ["Quattuorseptuagintacentillion", ""],
    ["Quinquaseptuagintacentillion", ""],
    ["Seseptuagintacentillion", ""],
    ["Septenseptuagintacentillion", ""],
    ["Octoseptuagintacentillion", ""],
    ["Novenseptuagintacentillion", ""],
    ["Octogintacentillion", ""],
    ["Unoctogintacentillion", ""],
    ["Duooctogintacentillion", ""],
    ["Tresoctogintacentillion", ""],
    ["Quattuoroctogintacentillion", ""],
    ["Quinquaoctogintacentillion", ""],
    ["Sexoctogintacentillion", ""],
    ["Septemoctogintacentillion", ""],
    ["Octooctogintacentillion", ""],
    ["Novemoctogintacentillion", ""],
    ["Nonagintacentillion", ""],
    ["Unnonagintacentillion", ""],
    ["Duononagintacentillion", ""],
    ["Trenonagintacentillion", ""],
    ["Quattuornonagintacentillion", ""],
    ["Quinquanonagintacentillion", ""],
    ["Senonagintacentillion", ""],
    ["Septenonagintacentillion", ""],
    ["Octononagintacentillion", ""],
    ["Novenonagintacentillion", ""],
    ["Ducentillion", ""],
    ["Unducentillion", ""],
    ["Duoducentillion", ""],
    ["Treducentillion", ""],
    ["Quattuorducentillion", ""],
    ["Quinquaducentillion", ""],
    ["Seducentillion", ""],
    ["Septenducentillion", ""],
    ["Octoducentillion", ""],
    ["Novenducentillion", ""],
    ["Deciducentillion", ""],
    ["Undeciducentillion", ""],
    ["Duodeciducentillion", ""],
    ["Tredeciducentillion", ""],
    ["Quattuordeciducentillion", ""],
    ["Quinquadeciducentillion", ""],
    ["Sedeciducentillion", ""],
    ["Septendeciducentillion", ""],
    ["Octodeciducentillion", ""],
    ["Novendeciducentillion", ""],
    ["Vigintiducentillion", ""],
    ["Unvigintiducentillion", ""],
    ["Duovigintiducentillion", ""],
    ["Tresvigintiducentillion", ""],
    ["Quattuorvigintiducentillion", ""],
    ["Quinquavigintiducentillion", ""],
    ["Sesvigintiducentillion", ""],
    ["Septemvigintiducentillion", ""],
    ["Octovigintiducentillion", ""],
    ["Novemvigintiducentillion", ""],
    ["Trigintaducentillion", ""],
    ["Untrigintaducentillion", ""],
    ["Duotrigintaducentillion", ""],
    ["Trestrigintaducentillion", ""],
    ["Quattuortrigintaducentillion", ""],
    ["Quinquatrigintaducentillion", ""],
    ["Sestrigintaducentillion", ""],
    ["Septentrigintaducentillion", ""],
    ["Octotrigintaducentillion", ""],
    ["Noventrigintaducentillion", ""],
    ["Quadragintaducentillion", ""],
    ["Unquadragintaducentillion", ""],
    ["Duoquadragintaducentillion", ""],
    ["Tresquadragintaducentillion", ""],
    ["Quattuorquadragintaducentillion", ""],
    ["Quinquaquadragintaducentillion", ""],
    ["Sesquadragintaducentillion", ""],
    ["Septenquadragintaducentillion", ""],
    ["Octoquadragintaducentillion", ""],
    ["Novenquadragintaducentillion", ""],
    ["Quinquagintaducentillion", ""],
    ["Unquinquagintaducentillion", ""],
    ["Duoquinquagintaducentillion", ""],
    ["Tresquinquagintaducentillion", ""],
    ["Quattuorquinquagintaducentillion", ""],
    ["Quinquaquinquagintaducentillion", ""],
    ["Sesquinquagintaducentillion", ""],
    ["Septenquinquagintaducentillion", ""],
    ["Octoquinquagintaducentillion", ""],
    ["Novenquinquagintaducentillion", ""],
    ["Sexagintaducentillion", ""],
    ["Unsexagintaducentillion", ""],
    ["Duosexagintaducentillion", ""],
    ["Tresexagintaducentillion", ""],
    ["Quattuorsexagintaducentillion", ""],
    ["Quinquasexagintaducentillion", ""],
    ["Sesexagintaducentillion", ""],
    ["Septensexagintaducentillion", ""],
    ["Octosexagintaducentillion", ""],
    ["Novensexagintaducentillion", ""],
    ["Septuagintaducentillion", ""],
    ["Unseptuagintaducentillion", ""],
    ["Duoseptuagintaducentillion", ""],
    ["Treseptuagintaducentillion", ""],
    ["Quattuorseptuagintaducentillion", ""],
    ["Quinquaseptuagintaducentillion", ""],
    ["Seseptuagintaducentillion", ""],
    ["Septenseptuagintaducentillion", ""],
    ["Octoseptuagintaducentillion", ""],
    ["Novenseptuagintaducentillion", ""],
    ["Octogintaducentillion", ""],
    ["Unoctogintaducentillion", ""],
    ["Duooctogintaducentillion", ""],
    ["Tresoctogintaducentillion", ""],
    ["Quattuoroctogintaducentillion", ""],
    ["Quinquaoctogintaducentillion", ""],
    ["Sexoctogintaducentillion", ""],
    ["Septemoctogintaducentillion", ""],
    ["Octooctogintaducentillion", ""],
    ["Novemoctogintaducentillion", ""],
    ["Nonagintaducentillion", ""],
    ["Unnonagintaducentillion", ""],
    ["Duononagintaducentillion", ""],
    ["Trenonagintaducentillion", ""],
    ["Quattuornonagintaducentillion", ""],
    ["Quinquanonagintaducentillion", ""],
    ["Senonagintaducentillion", ""],
    ["Septenonagintaducentillion", ""],
    ["Octononagintaducentillion", ""],
    ["Novenonagintaducentillion", ""],
    ["Trecentillion", ""],
    ["Untrecentillion", ""],
    ["Duotrecentillion", ""],
    ["Trestrecentillion", ""],
    ["Quattuortrecentillion", ""],
    ["Quinquatrecentillion", ""],
    ["Sestrecentillion", ""],
    ["Septentrecentillion", ""],
    ["Octotrecentillion", ""],
    ["Noventrecentillion", ""],
    ["Decitrecentillion", ""],
    ["Undecitrecentillion", ""],
    ["Duodecitrecentillion", ""],
    ["Tredecitrecentillion", ""],
    ["Quattuordecitrecentillion", ""],
    ["Quinquadecitrecentillion", ""],
    ["Sedecitrecentillion", ""],
    ["Septendecitrecentillion", ""],
    ["Octodecitrecentillion", ""],
    ["Novendecitrecentillion", ""],
    ["Vigintitrecentillion", ""],
    ["Unvigintitrecentillion", ""],
    ["Duovigintitrecentillion", ""],
    ["Tresvigintitrecentillion", ""],
    ["Quattuorvigintitrecentillion", ""],
    ["Quinquavigintitrecentillion", ""],
    ["Sesvigintitrecentillion", ""],
    ["Septemvigintitrecentillion", ""],
    ["Octovigintitrecentillion", ""],
    ["Novemvigintitrecentillion", ""],
    ["Trigintatrecentillion", ""],
    ["Untrigintatrecentillion", ""],
    ["Duotrigintatrecentillion", ""],
    ["Trestrigintatrecentillion", ""] // 1998 zeros after digit and is 10^1998
]

const formatNumber = (number, shorthand=false) => {
    /* 
        Pretifies numbers by placing them in a shorthand(ish) format

        Shorthand is an argument which decides whether to use a couple of
        letters for the prefix or use the full name

        124232 -> 124.23 Thousand or 124.23 K
        
        NOTE: The value is truncated, not rounded
    */
   
    let value = ""

    if (number instanceof BigNumber) {
        value = number.toString(10)
    } else {
        value = `${ number }`
    }
    

    // NOTE: Not the actual number of zeros!
    const numberZeros = (value.length - 1)
    
    if (numberZeros < 3) {
        return value
    } else {
        const suffixPosition = (numberZeros/3 << 0) - 1
        let suffix = ""
        const rm0 = ((suffixPosition + 1) * 3) - 2

        // Hopefully handles if the number hasn't been added yet
        if (suffixPosition > (suffixList.length - 1)) {
            suffix = shorthand ? "?" : "????????????"
        } else {
            suffix = suffixList[suffixPosition][+shorthand] // +shorthand converts a boolean into an integer of either 1 or 0 which is the position in the list
        }

        const actualValue = value.slice(0, -rm0)
        const formattedValue = `${ actualValue.slice(0, -2) }.${ actualValue.slice(-2) } ${ suffix }`

        return formattedValue
    }        
}

